# Exported from Render on 2025-10-03T10:23:00Z
version: "1"
services:
- type: web
  name: "[ALPHA] AI Loom Frontend"
  runtime: static
  repo: https://github.com/vox-hunter/learnify
  branch: alpha
  envVars:
  - key: VITE_API_URL
    sync: false
  buildCommand: cd vue-frontend && VITE_API_URL=https://ai-loom-backend.onrender.com
    npm install && npm run build
  staticPublishPath: vue-frontend/dist
  routes:
  - type: rewrite
    source: /api/*
    destination: https://learnify-backend.onrender.com/api/*
  autoDeployTrigger: commit
