"""
Google OAuth Implementation for FastAPI + Vue
==============================================
Handles OAuth 2.0 flow for Google authentication in production.
"""

import os
import requests
from typing import Optional, Dict, Any
from urllib.parse import urlencode
from dotenv import load_dotenv

load_dotenv()

# Google OAuth Configuration
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

# Production redirect URIs (must match Google Cloud Console settings)
ALLOWED_REDIRECT_URIS = {
    "https://app.ailoom.me/auth/google/callback",
    "https://alpha-ai-loom-frontend.onrender.com/auth/google/callback",
}

# Google OAuth endpoints
GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_URL = "https://www.googleapis.com/oauth2/v2/userinfo"


def verify_oauth_config() -> bool:
    """Verify that OAuth configuration is properly set up"""
    if not GOOGLE_CLIENT_ID or GOOGLE_CLIENT_ID == "your-google-client-id":
        return False
    if not GOOGLE_CLIENT_SECRET or GOOGLE_CLIENT_SECRET == "your-google-client-secret":
        return False
    return True


def get_google_auth_url(redirect_uri: str, state: str) -> Optional[str]:
    """
    Generate Google OAuth authorization URL
    
    Args:
        redirect_uri: The frontend callback URL
        state: CSRF protection token (generated by frontend)
    
    Returns:
        Google OAuth URL or None if config is invalid
    """
    if not verify_oauth_config():
        return None
    
    if redirect_uri not in ALLOWED_REDIRECT_URIS:
        raise ValueError(f"Redirect URI not allowed: {redirect_uri}")
    
    params = {
        "client_id": GOOGLE_CLIENT_ID,
        "redirect_uri": redirect_uri,
        "response_type": "code",
        "scope": "openid email profile",
        "access_type": "online",
        "state": state,
        "prompt": "select_account"
    }
    
    return f"{GOOGLE_AUTH_URL}?{urlencode(params)}"


def exchange_code_for_token(code: str, redirect_uri: str) -> Optional[Dict[str, Any]]:
    """
    Exchange authorization code for access token
    
    Args:
        code: Authorization code from Google
        redirect_uri: Must match the one used in auth URL
    
    Returns:
        Token response dict or None if exchange fails
    """
    if not verify_oauth_config():
        raise ValueError("Google OAuth not configured")
    
    if redirect_uri not in ALLOWED_REDIRECT_URIS:
        raise ValueError(f"Redirect URI not allowed: {redirect_uri}")
    
    data = {
        "code": code,
        "client_id": GOOGLE_CLIENT_ID,
        "client_secret": GOOGLE_CLIENT_SECRET,
        "redirect_uri": redirect_uri,
        "grant_type": "authorization_code"
    }
    
    try:
        response = requests.post(GOOGLE_TOKEN_URL, data=data, timeout=10)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error exchanging code for token: {e}")
        return None


def get_user_info(access_token: str) -> Optional[Dict[str, Any]]:
    """
    Get user information from Google using access token
    
    Args:
        access_token: OAuth access token
    
    Returns:
        User info dict with email, name, picture, etc.
    """
    headers = {
        "Authorization": f"Bearer {access_token}"
    }
    
    try:
        response = requests.get(GOOGLE_USERINFO_URL, headers=headers, timeout=10)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error getting user info: {e}")
        return None


def validate_google_oauth_user(user_info: Dict[str, Any]) -> Dict[str, Any]:
    """
    Validate and extract relevant user information from Google OAuth response
    
    Args:
        user_info: Raw user info from Google
    
    Returns:
        Validated user data dict
    """
    print(f"[Google OAuth] Raw user_info from Google: {user_info}")
    
    if not user_info.get("email"):
        raise ValueError("No email in user info")
    
    if not user_info.get("verified_email", False):
        raise ValueError("Email not verified by Google")
    
    google_id = user_info.get("sub") or user_info.get("id", "")
    print(f"[Google OAuth] Extracted google_id: {google_id}")
    
    return {
        "email": user_info["email"],
        "name": user_info.get("name", ""),
        "given_name": user_info.get("given_name", ""),
        "family_name": user_info.get("family_name", ""),
        "picture": user_info.get("picture", ""),
        "google_id": google_id,
        "email_verified": True  # Google has already verified
    }
