import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../components/ui/Button';

export const TermsPage: React.FC = () => {
  const navigate = useNavigate();
  const lastUpdated = 'September 29, 2025';

  return (
    <div className="terms-page">
      <div className="legal-header">
        <Button
          onClick={() => navigate(-1)}
          variant="ghost"
          leftIcon="←"
          className="back-button"
        >
          Back
        </Button>
        <h1>Terms of Service</h1>
        <p className="last-updated">Last updated: {lastUpdated}</p>
      </div>

      <div className="legal-content">
        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Learnify ("Service"), you agree to be bound by these Terms of Service ("Terms"). 
            If you disagree with any part of these terms, you may not access the Service.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Service</h2>
          <p>
            Learnify is an AI-powered learning platform that transforms documents and web content into 
            interactive educational materials, including quizzes, flashcards, and personalized learning experiences.
          </p>
          <p>Our service includes:</p>
          <ul>
            <li>Document upload and processing capabilities</li>
            <li>AI-generated educational content creation</li>
            <li>Interactive quiz and assessment tools</li>
            <li>Progress tracking and analytics</li>
            <li>Personalized learning recommendations</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>3. User Accounts</h2>
          <p>To use certain features of our Service, you must create an account. You agree to:</p>
          <ul>
            <li>Provide accurate, current, and complete information</li>
            <li>Maintain and update your account information</li>
            <li>Keep your password secure and confidential</li>
            <li>Notify us immediately of any unauthorized access</li>
            <li>Accept responsibility for all activities under your account</li>
          </ul>
          <p>
            You must be at least 13 years old to create an account. Users between 13-18 must have 
            parental consent.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. Acceptable Use</h2>
          <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree NOT to:</p>
          <ul>
            <li>Upload copyrighted content without proper authorization</li>
            <li>Share harmful, offensive, or inappropriate content</li>
            <li>Attempt to circumvent security measures or access restrictions</li>
            <li>Use the Service to spam, harass, or harm others</li>
            <li>Reverse engineer, decompile, or attempt to extract source code</li>
            <li>Use automated systems to access the Service without permission</li>
            <li>Impersonate others or provide false information</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>5. Content and Intellectual Property</h2>
          <h3>Your Content</h3>
          <p>
            You retain ownership of content you upload ("User Content"). By uploading content, you grant 
            Learnify a license to:
          </p>
          <ul>
            <li>Process and analyze your content to generate educational materials</li>
            <li>Store and display your content as part of the Service</li>
            <li>Use your content to improve our AI algorithms and services</li>
          </ul>
          
          <h3>Generated Content</h3>
          <p>
            Educational materials generated by our AI from your content ("Generated Content") are provided 
            for your personal learning use. You may use Generated Content for educational purposes but may 
            not resell or redistribute it commercially.
          </p>
          
          <h3>Our Content</h3>
          <p>
            The Service, including its design, features, and underlying technology, is owned by Learnify 
            and protected by copyright, trademark, and other intellectual property laws.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. Privacy and Data Protection</h2>
          <p>
            Your privacy is important to us. Our collection, use, and protection of your personal information 
            is governed by our <a href="/privacy" className="legal-link">Privacy Policy</a>, which is 
            incorporated into these Terms by reference.
          </p>
        </section>

        <section className="legal-section">
          <h2>7. Payment and Subscription Terms</h2>
          <p>If you purchase a paid subscription:</p>
          <ul>
            <li>Fees are charged in advance and are non-refundable except as required by law</li>
            <li>Subscriptions automatically renew unless cancelled</li>
            <li>You can cancel anytime through your account settings</li>
            <li>Price changes will be communicated 30 days in advance</li>
            <li>We reserve the right to change pricing with notice</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>8. Service Availability</h2>
          <p>
            We strive to provide reliable service but cannot guarantee uninterrupted access. The Service may be 
            temporarily unavailable due to:
          </p>
          <ul>
            <li>Scheduled maintenance and updates</li>
            <li>Technical difficulties or server issues</li>
            <li>Circumstances beyond our reasonable control</li>
          </ul>
          <p>
            We will make reasonable efforts to provide advance notice of planned downtime.
          </p>
        </section>

        <section className="legal-section">
          <h2>9. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW:
          </p>
          <ul>
            <li>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND</li>
            <li>WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED</li>
            <li>WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES</li>
            <li>OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID IN THE LAST 12 MONTHS</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>10. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Learnify, its officers, directors, employees, and agents 
            from any claims, damages, or expenses arising from:
          </p>
          <ul>
            <li>Your use of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your violation of any rights of another party</li>
            <li>Content you upload or share through the Service</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>11. Termination</h2>
          <p>
            Either party may terminate your account at any time:
          </p>
          <ul>
            <li><strong>By You:</strong> Delete your account through account settings</li>
            <li><strong>By Us:</strong> For violation of these Terms or at our discretion with notice</li>
          </ul>
          <p>
            Upon termination:
          </p>
          <ul>
            <li>Your access to the Service will cease immediately</li>
            <li>Your data may be deleted according to our retention policy</li>
            <li>These Terms will continue to apply to past use of the Service</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>12. Dispute Resolution</h2>
          <p>
            Any disputes arising from these Terms or your use of the Service will be resolved through:
          </p>
          <ul>
            <li><strong>Informal Resolution:</strong> Contact us first to resolve disputes amicably</li>
            <li><strong>Binding Arbitration:</strong> Unresolved disputes will be settled by arbitration</li>
            <li><strong>Class Action Waiver:</strong> You waive the right to participate in class actions</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the jurisdiction where Learnify is incorporated, 
            without regard to conflict of law principles.
          </p>
        </section>

        <section className="legal-section">
          <h2>14. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will notify you of material changes by:
          </p>
          <ul>
            <li>Posting updated Terms on our website</li>
            <li>Sending email notifications to registered users</li>
            <li>Displaying notices within the Service</li>
          </ul>
          <p>
            Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>15. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions will 
            continue in full force and effect.
          </p>
        </section>

        <section className="legal-section">
          <h2>16. Contact Information</h2>
          <p>
            For questions about these Terms or our Service, please contact us:
          </p>
          <div className="contact-info">
            <p><strong>Email:</strong> <a href="mailto:legal@learnify.com">legal@learnify.com</a></p>
            <p><strong>Mail:</strong> Learnify Legal Team, 123 Learning Street, Education City, EC 12345</p>
            <p><strong>Phone:</strong> +1 (555) 123-LEARN</p>
          </div>
        </section>
      </div>

      <div className="legal-footer">
        <p className="acknowledgment">
          By using Learnify, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
        </p>
        <Button
          onClick={() => navigate('/')}
          variant="primary"
          size="lg"
        >
          Back to Home
        </Button>
      </div>
    </div>
  );
};