<template>
  <div class="terms-view">
    <div class="container-sm">
      <div class="content-card card">
        <h1 class="page-title">Terms & Conditions</h1>
        
        <div class="content">
          <section class="section">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Learnify, you accept and agree to be bound by these Terms and Conditions. 
              If you do not agree to these terms, please do not use our platform.
            </p>
          </section>

          <section class="section">
            <h2>2. Use of Service</h2>
            <p>Learnify provides an AI-powered platform for generating educational courses and quizzes from documents.</p>
            <ul>
              <li>You must be at least 13 years old to use this service</li>
              <li>You are responsible for maintaining the confidentiality of your account</li>
              <li>You agree to provide accurate and complete information</li>
              <li>One person or legal entity may not maintain multiple accounts</li>
            </ul>
          </section>

          <section class="section">
            <h2>3. Content and Intellectual Property</h2>
            <p><strong>Your Content:</strong></p>
            <ul>
              <li>You retain ownership of any documents you upload</li>
              <li>By uploading content, you grant us a license to process it for course generation</li>
              <li>You are responsible for ensuring you have the right to upload and process any content</li>
              <li>You must not upload copyrighted material without permission</li>
            </ul>
            
            <p><strong>Generated Content:</strong></p>
            <ul>
              <li>Courses generated by our AI belong to you</li>
              <li>We may use anonymized data to improve our services</li>
              <li>AI-generated content is provided "as is" and may contain errors</li>
            </ul>

            <p><strong>Our Platform:</strong></p>
            <ul>
              <li>Learnify and its original content, features, and functionality are owned by us</li>
              <li>You may not copy, modify, or distribute our platform without permission</li>
            </ul>
          </section>

          <section class="section">
            <h2>4. Acceptable Use</h2>
            <p>You agree NOT to:</p>
            <ul>
              <li>Use the service for any illegal purpose</li>
              <li>Upload malicious code or viruses</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the service</li>
              <li>Use the service to harass, abuse, or harm others</li>
              <li>Circumvent any limitations on your account</li>
            </ul>
          </section>

          <section class="section">
            <h2>5. AI-Generated Content</h2>
            <p>
              Our platform uses Google's Gemini AI to generate course content. Please note:
            </p>
            <ul>
              <li>AI-generated content may contain inaccuracies</li>
              <li>You should verify important information independently</li>
              <li>We are not responsible for errors in AI-generated content</li>
              <li>The quality of generated content depends on your input documents</li>
            </ul>
          </section>

          <section class="section">
            <h2>6. Privacy and Data</h2>
            <p>
              Your privacy is important to us. Please review our 
              <router-link to="/privacy">Privacy Policy</router-link> to understand how we collect, 
              use, and protect your information.
            </p>
          </section>

          <section class="section">
            <h2>7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Learnify shall not be liable for:
            </p>
            <ul>
              <li>Any indirect, incidental, special, or consequential damages</li>
              <li>Loss of profits, data, or business opportunities</li>
              <li>Errors or inaccuracies in AI-generated content</li>
              <li>Interruptions or unavailability of the service</li>
            </ul>
            <p>
              The service is provided "as is" without warranties of any kind, express or implied.
            </p>
          </section>

          <section class="section">
            <h2>8. Account Termination</h2>
            <p>We reserve the right to:</p>
            <ul>
              <li>Suspend or terminate your account for violation of these terms</li>
              <li>Remove any content that violates our policies</li>
              <li>Refuse service to anyone at our discretion</li>
            </ul>
            <p>
              You may delete your account at any time by contacting us or using the account 
              deletion feature in your settings.
            </p>
          </section>

          <section class="section">
            <h2>9. Service Modifications</h2>
            <p>
              We reserve the right to:
            </p>
            <ul>
              <li>Modify or discontinue the service at any time</li>
              <li>Change pricing or features with notice</li>
              <li>Update these terms and conditions</li>
            </ul>
            <p>
              Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section class="section">
            <h2>10. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with applicable laws, 
              without regard to conflict of law provisions.
            </p>
          </section>

          <section class="section">
            <h2>11. Contact Information</h2>
            <p>
              If you have questions about these Terms and Conditions, please contact us through 
              our platform support system.
            </p>
          </section>

          <div class="last-updated">
            <p><strong>Last Updated:</strong> January 2024</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TermsView'
}
</script>

<style scoped>
.terms-view {
  padding: 2rem 0;
  min-height: calc(100vh - 200px);
}

.content-card {
  max-width: 800px;
  margin: 0 auto;
}

.page-title {
  font-size: 2.5rem;
  font-weight: 700;
  color: #e2e8f0;
  margin-bottom: 2rem;
  text-align: center;
}

.content {
  color: #cbd5e0;
  line-height: 1.8;
}

.section {
  margin-bottom: 2rem;
}

.section h2 {
  font-size: 1.75rem;
  font-weight: 600;
  color: #06b6d4;
  margin-bottom: 1rem;
}

.section p {
  margin-bottom: 1rem;
}

.section ul {
  margin-left: 1.5rem;
  margin-bottom: 1rem;
}

.section li {
  margin-bottom: 0.5rem;
}

.section a {
  color: #06b6d4;
  text-decoration: underline;
}

.section a:hover {
  color: #0891b2;
}

.last-updated {
  margin-top: 3rem;
  padding-top: 2rem;
  border-top: 2px solid rgba(6, 182, 212, 0.2);
  text-align: center;
  font-size: 0.875rem;
}

@media (max-width: 768px) {
  .page-title {
    font-size: 2rem;
  }

  .section h2 {
    font-size: 1.5rem;
  }
}
</style>
