"""
Home Page - Main course generation interface
"""
import streamlit as st
import sys
import os
from streamlit_cookies_manager import EncryptedCookieManager
import io

# Add parent directory to path to import modules
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

# Add the parent directory (Quiz app) to sys.path to allow imports from it
# __file__ is pages/1_🏠_Home.py -> dirname is pages -> dirname is Quiz app
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import loading animation utilities if available
try:
    from loading_animation import show_loading_status
    from streamlit_loading import ensure_loading_cleanup
    
    # Ensure loading UI is cleaned up on this page
    ensure_loading_cleanup()
except ImportError:
    def show_loading_status(message, progress=None):
        pass  # Fallback if loading animation is not available

try:
    from mongo_auth import MongoAuthManager
    from mongo_course_manager import get_course_manager, get_session_id
    from local_backend import analyze_pdf_content, generate_course
    MONGO_AVAILABLE = True
except ImportError as e:
    # It's okay to call st.error here after set_page_config
    st.error(f"Failed to import MongoAuthManager or MongoCourseManager. Ensure mongo_auth.py and mongo_course_manager.py are in the correct path: {e}")
    MONGO_AVAILABLE = False
    # Allow guest access even if Mongo is down, but authenticated features will be limited.

# --- Get Cookie Manager from Session State ---
cookies = st.session_state.get('cookies')
if cookies is None:
    # Try fallback initialization
    try:
        from cookie_fallback import ensure_cookie_manager
        if ensure_cookie_manager():
            cookies = st.session_state.get('cookies')
        else:
            st.error("Cookie manager not found in session state. Please run the app from the main entry point.")
            st.markdown("Please refresh the page or go back to the [Home page](/) to start the application properly.")
            st.stop()
    except ImportError:
        st.error("Cookie manager not found in session state. Please run the app from the main entry point.")
        st.markdown("Please refresh the page or go back to the [Home page](/) to start the application properly.")
        st.stop()

# Initialize cookies if they haven't been, e.g. on first run
# This needs to be called early, but after st.set_page_config
# Note: On some deployment platforms, cookies might take time to initialize
try:
    cookies_ready = cookies is not None and cookies.ready()
except Exception:
    cookies_ready = False

AUTH_COOKIE_NAME = "username" # Consistent cookie name
GUEST_COURSES_COOKIE_NAME = "guest_courses_count" # Cookie to track guest course generation

# --- Authentication is now handled in main.py ---

# --- Guest Course Tracking Functions ---
def get_guest_course_count():
    """Get the number of courses generated by guest users from cookies"""
    if cookies is None:
        return 0
    try:
        if not cookies.ready():
            return 0
    except Exception:
        return 0
    try:
        return int(cookies.get(GUEST_COURSES_COOKIE_NAME, "0"))
    except (ValueError, TypeError):
        return 0

def increment_guest_course_count():
    """Increment the guest course count in cookies"""
    if cookies is None:
        return
    try:
        if not cookies.ready():
            return
    except Exception:
        return
    current_count = get_guest_course_count()
    new_count = current_count + 1
    try:
        cookies[GUEST_COURSES_COOKIE_NAME] = str(new_count)
        cookies.save()
    except Exception:
        pass  # Ignore cookie errors
    return new_count

def reset_guest_course_count():
    """Reset guest course count (called when user logs in)"""
    if cookies is None:
        return
    try:
        if cookies.ready():
            cookies[GUEST_COURSES_COOKIE_NAME] = "0"
            cookies.save()
    except Exception:
        pass  # Ignore cookie errors

def check_course_limit():
    """Check if user has reached the course generation limit"""
    if st.session_state.get('authentication_status'):
        return True # No limit for logged-in users
    
    # For guest users, check cookie-based count
    guest_count = get_guest_course_count()
    return guest_count < 3

def force_login_if_limit_reached():
    """Force login if guest user has reached the 3-course limit"""
    if st.session_state.get('authentication_status'):
        return False  # Already logged in
    
    guest_count = get_guest_course_count()
    if guest_count >= 3:
        st.warning("You have reached the guest limit of 3 courses. Please log in to create more.")
        st.page_link("pages/2_🔐_Login.py", label="Login / Sign Up", icon="🔐")
        st.stop()
    return False

# Initialize session state function
def initialize_session_state():
    """Initialize all session state variables"""
    if "current_section_index" not in st.session_state:  
        st.session_state.current_section_index = 0
    if "user_answers" not in st.session_state:
        st.session_state.user_answers = {}
    if "checked_answers" not in st.session_state:
        st.session_state.checked_answers = {}
    if "current_score" not in st.session_state:
        st.session_state.current_score = 0
    if "total_questions_in_course" not in st.session_state:
        st.session_state.total_questions_in_course = 0
    if "scored_correctly_keys" not in st.session_state:
        st.session_state.scored_correctly_keys = set()
    if "feedback" not in st.session_state:
        st.session_state.feedback = {}
    if "course_data" not in st.session_state:
        st.session_state.course_data = None
    if "error_message" not in st.session_state:
        st.session_state.error_message = None
    if "is_generating_course" not in st.session_state:
        st.session_state.is_generating_course = False
    if "courses_generated" not in st.session_state:
        # For guest users, load count from cookies; for logged-in users, always 0
        if st.session_state.get('authentication_status'):
            st.session_state.courses_generated = 0
        else:
            st.session_state.courses_generated = get_guest_course_count()
    if "authentication_status" not in st.session_state:
        st.session_state.authentication_status = None
    if "name" not in st.session_state:
        st.session_state.name = None
    if "username" not in st.session_state:
        st.session_state.username = None
    if "course_history" not in st.session_state:
        st.session_state.course_history = []
    if "current_course_id" not in st.session_state:
        st.session_state.current_course_id = None

# Initialize session state
initialize_session_state()

# Apply modern CSS styling
st.markdown("""
<style>
    /* Global styles */
    .stApp {
        background: linear-gradient(135deg, #0a0014 0%, #1a0033 100%);
    }
    
    /* Hide default sidebar */
    .css-1d391kg {
        padding-top: 1rem;
    }
    
    /* Center container */
    .main-container {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        text-align: center;
    }
    
    /* Title styling */
    .main-title {
        font-size: 3rem;
        font-weight: 700;
        background: linear-gradient(135deg, #9d00ff, #ff6b6b);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 2rem;
    }
      /* Pill button styling */
    .stButton > button {
        background: linear-gradient(135deg, #9d00ff, #7a00cc);
        color: white;
        border: none;
        border-radius: 50px;
        padding: 12px 30px;
        font-weight: 600;
        transition: all 0.3s ease;
        box-shadow: 0 4px 15px rgba(157, 0, 255, 0.3);
        width: 100%;
        font-size: 1rem;
    }
    
    .stButton > button:hover {
        background: linear-gradient(135deg, #7a00cc, #5c0099);
        transform: translateY(-2px);
        box-shadow: 0 8px 25px rgba(157, 0, 255, 0.4);
    }
    
    /* Input styling */
    .stTextInput > div > div > input {
        background: rgba(26, 0, 51, 0.8);
        border: 2px solid #9d00ff;
        border-radius: 25px;
        color: #ededed;
        padding: 12px 20px;
    }
    
    .stTextInput > div > div > input:focus {
        border-color: #ff6b6b;
        box-shadow: 0 0 15px rgba(157, 0, 255, 0.3);
    }
    
    /* File uploader enhanced styling */
    .stFileUploader {
        background: rgba(255, 255, 255, 0.03);
        border: 2px dashed #9d00ff;
        border-radius: 20px;
        padding: 2rem;
        text-align: center;
        transition: all 0.3s ease;
        margin: 1rem 0;
    }
    
    .stFileUploader:hover {
        border-color: #ff6b6b;
        background: rgba(255, 255, 255, 0.06);
        transform: translateY(-2px);
    }
    
    /* Tab styling */
    .stTabs [data-baseweb="tab-list"] {
        background: rgba(255, 255, 255, 0.05);
        border-radius: 25px;
        padding: 5px;
        gap: 10px;
        justify-content: center;
        margin-bottom: 2rem;
    }
    
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        border-radius: 20px;
        color: rgba(255, 255, 255, 0.7);
        padding: 12px 24px;
        font-weight: 600;
        transition: all 0.3s ease;
        border: none;
    }
    
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #9d00ff, #7a00cc);
        color: white;
        box-shadow: 0 4px 15px rgba(157, 0, 255, 0.3);
    }
    
    /* Progress bar styling */
    .stProgress > div > div > div > div {
        background: linear-gradient(135deg, #9d00ff, #ff6b6b);
        border-radius: 10px;
    }
    
    /* Success/Error/Warning message styling */
    .stSuccess, .stInfo, .stWarning, .stError {
        border-radius: 15px;
        border: none;
        padding: 1rem;
        margin: 1rem 0;
    }
    
    .stSuccess {
        background: linear-gradient(135deg, rgba(0, 255, 0, 0.1), rgba(0, 200, 0, 0.1));
        border-left: 4px solid #00ff00;
    }
    
    .stInfo {
        background: linear-gradient(135deg, rgba(0, 150, 255, 0.1), rgba(0, 100, 255, 0.1));
        border-left: 4px solid #0096ff;
    }
    
    .stWarning {
        background: linear-gradient(135deg, rgba(255, 165, 0, 0.1), rgba(255, 140, 0, 0.1));
        border-left: 4px solid #ffa500;
    }
    
    .stError {
        background: linear-gradient(135deg, rgba(255, 0, 0, 0.1), rgba(200, 0, 0, 0.1));
        border-left: 4px solid #ff0000;
    }
    
    /* Top navigation */
    .top-nav {
        position: fixed;
        top: 0;
        right: 0;
        padding: 1rem;
        z-index: 1000;
    }
</style>
""", unsafe_allow_html=True)

def main():
    # Check if a course_id is provided in the URL for sharing
    shared_course_id = st.query_params.get("course_id")
    if shared_course_id:
        # Store in session state to ensure it survives any redirects
        st.session_state.shared_course_id = shared_course_id
        
        # Redirect immediately without any other processing
        st.query_params["course_id"] = shared_course_id
        st.switch_page("pages/3_Course.py")
        return
    
    # Process logout flag and attempt auto-login
    just_logged_out = st.session_state.pop('logout_just_occurred', False)
    
    if just_logged_out:
        st.session_state['logout_just_occurred_processed_auto_login_home'] = True # Mark that this specific reload after logout has been processed for auto-login
    else:        # If not just logged out, clear the processed flag
        st.session_state.pop('logout_just_occurred_processed_auto_login_home', None)
        # Attempt auto-login only if cookies are ready and not immediately after a logout action
        if cookies is not None:
            try:
                if cookies.ready():
                    pass # auto_login_from_cookie() is in main.py
            except Exception:
                pass
      # Top navigation
    _, col2, col3 = st.columns([6, 1, 1])  # Adjusted column ratio for better spacing
    
    with col2: # Login/User status
        if st.session_state.get('authentication_status'):
            # Display user name, truncate if too long for the button-like display
            display_name = st.session_state.get('name', st.session_state.get('username', 'User'))
            if len(display_name) > 15:
                display_name = display_name[:12] + "..."
            st.markdown(f"<div style='text-align: center; padding: 5px 0px; border: 1px solid #9d00ff; border-radius: 25px; background: rgba(157,0,255,0.1); color: #ededed;'>👤 {display_name}</div>", unsafe_allow_html=True)
        elif MONGO_AVAILABLE and cookies is not None:
            try:
                if cookies.ready():
                    if st.button("🔐 Login", key="top_nav_login_btn", use_container_width=True):
                        st.switch_page("pages/2_🔐_Login.py")
            except Exception:
                if st.button("🔐 Login", key="top_nav_login_btn", use_container_width=True):
                    st.switch_page("pages/2_🔐_Login.py")
        # If not authenticated and auth unavailable, this column remains empty or shows a guest indicator if desired


    # Main content container
    st.markdown('<div class="main-container">', unsafe_allow_html=True)
      # Main title
    st.markdown('<h1 class="main-title">What will you learn today?</h1>', unsafe_allow_html=True)    # Show status message
    if st.session_state.get('authentication_status'):
        st.success(f"🎉 Welcome back, {st.session_state.get('name', 'User')}! You have unlimited course generation.")
    else:
        # Force login if limit reached
        if force_login_if_limit_reached():
            return  # Stop execution if forcing login            
        # Show remaining courses for guest users
        guest_count = get_guest_course_count()
        remaining = 3 - guest_count
        if remaining > 0:
            st.info(f"🎯 Guest mode: {remaining} out of 3 free courses remaining")
        else:
            st.warning("🔒 You've used all 3 guest courses. Please login for unlimited access!")

    # Input tabs
    tab1, tab2 = st.tabs(["📁 Upload File", "🔗 URL"])
    uploaded_file = None
    pdf_url = None
    
    with tab1:
        st.markdown("### Upload your PDF file")
        uploaded_file = st.file_uploader(
            "Choose a PDF file",
            type=["pdf"],
            help="Large files will be automatically compressed during course generation. Maximum words: 15,000",
            label_visibility="collapsed"
        )
        if uploaded_file:
            file_size = len(uploaded_file.getvalue())
            file_size_mb = file_size / (1024*1024)
              # Show file info and size warning if large
            if file_size > 10 * 1024 * 1024:
                st.warning(f"📦 Large file detected: {file_size_mb:.1f} MB (above 10MB limit)")
                st.info("💡 **Note:** File will be automatically compressed during course generation to fit within limits.")
            else:
                st.success(f"📄 File uploaded: {uploaded_file.name} ({file_size_mb:.1f} MB)")              # For large files, skip heavy analysis during upload to avoid delays
            if uploaded_file:
                if file_size > 10 * 1024 * 1024:
                    # Large file: do quick validation only
                    try:
                        # Quick test - try to read first few bytes to verify it's a valid PDF
                        file_content = uploaded_file.getvalue()
                        if not file_content.startswith(b'%PDF'):
                            st.error("❌ Invalid PDF file format detected.")
                            uploaded_file = None
                    except Exception as e:
                        st.error(f"❌ Error reading PDF file: {str(e)}")
                        uploaded_file = None
                else:
                    # Small file: do full analysis during upload as before
                    try:
                        pdf_analysis = analyze_pdf_content(uploaded_file.getvalue())
                        word_count = pdf_analysis['word_count']
                        
                        if word_count > 15000:
                            st.error(f"❌ PDF contains too many words ({word_count:,}). Maximum allowed: 15,000 words.")
                            st.info("💡 **Tip:** Try uploading a shorter document or specific chapters.")
                            uploaded_file = None
                        elif word_count == 0:
                            st.error("❌ Could not extract text from this PDF. Please try a different file.")
                            uploaded_file = None
                        else:
                            st.success(f"📄 File processed: {uploaded_file.name} ({file_size_mb:.1f} MB, {word_count:,} words)")
                            
                            if word_count > 12000:
                                st.warning("⚠️ Large document detected. Generation may take longer than usual.")
                                
                    except Exception as e:
                        st.error(f"❌ Error analyzing PDF: {str(e)}")
                        uploaded_file = None
    
    with tab2:
        st.markdown("### Enter PDF URL")
        pdf_url = st.text_input(
            "PDF URL",
            placeholder="https://example.com/document.pdf",
            help="Enter a direct link to a PDF file",
            label_visibility="collapsed"
        )
        if pdf_url and not pdf_url.startswith(('http://', 'https://')):
            st.warning("⚠️ Please enter a valid URL starting with http:// or https://")
            pdf_url = None
        elif pdf_url:
            st.warning("⚠️ **Limits:** Maximum 10MB file size, 15,000 words")
    
    # Generate button
    st.markdown("<br>", unsafe_allow_html=True)
    
    # Check if user can generate courses
    can_generate = check_course_limit()
    
    if st.session_state.get('is_generating_course', False):
        st.button("🤖 Generating Course...", disabled=True, key="generating_btn")        # Show progress
        show_generation_progress()
    elif can_generate:
        if st.button("✨ Generate Course", type="primary", key="generate_btn"):
            if uploaded_file or pdf_url:
                # Double-check course limit before generating
                if not check_course_limit():
                    st.error("🔐 Course limit reached. Please login to continue.")
                    return
                    
                # Store file data in session state for progress function
                st.session_state.current_uploaded_file = uploaded_file
                st.session_state.current_pdf_url = pdf_url
                
                # Set generating state immediately and rerun to update UI
                st.session_state.is_generating_course = True
                st.rerun()
            else:
                st.error("⚠️ Please upload a file or enter a URL first")
    else:
        st.warning("⚠️ You've reached the limit of 3 guest courses. Please login for unlimited access.")
        if st.button("🔐 Go to Login", type="primary"):
            st.switch_page("pages/2_🔐_Login.py")
    
    # Show course history in sidebar if available
    show_course_history()
    
    st.markdown('</div>', unsafe_allow_html=True)

def show_generation_progress():
    """Show course generation progress and start generation"""
    # Get the file data from session state (set when button was clicked)
    uploaded_file = st.session_state.get('current_uploaded_file')
    pdf_url = st.session_state.get('current_pdf_url')
    
    if uploaded_file or pdf_url:
        generate_and_redirect(uploaded_file, pdf_url)
    else:
        st.error("❌ No file or URL found for generation")

def generate_and_redirect(uploaded_file, pdf_url):
    """Generate course and redirect to course page with real-time progress"""
    # Set generation state
    st.session_state.is_generating_course = True
    
    # Create progress containers
    progress_container = st.container()
    with progress_container:
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        # Status callback function for real-time updates
        def status_callback(status_message, progress_percent):
            """Update progress and status in real-time"""
            progress_bar.progress(progress_percent / 100)
            status_text.text(status_message)
            import time
            time.sleep(1.5)  # Allow users to read the status
        
        try:
            # Handle file compression if needed before generation
            if uploaded_file:
                # Check file size and compress if necessary
                file_content = uploaded_file.read()
                file_size_mb = len(file_content) / (1024 * 1024)
                
                if file_size_mb > 10:
                    status_text.text(f"📦 Large file detected ({file_size_mb:.1f}MB). Compressing...")
                    progress_bar.progress(5)
                      # Compress the file
                    compressed_content, final_size_mb, _, _ = smart_pdf_compression(
                        file_content, target_size_mb=10
                    )
                    
                    if final_size_mb <= 10:
                        status_text.text(f"✅ Compression successful: {file_size_mb:.1f}MB → {final_size_mb:.1f}MB")
                        progress_bar.progress(10)
                        import time
                        time.sleep(1.0)  # Show compression success briefly
                        file_content = compressed_content
                    else:
                        # Compression didn't achieve target, but continue anyway
                        status_text.text(f"⚠️ Partial compression: {file_size_mb:.1f}MB → {final_size_mb:.1f}MB")
                        progress_bar.progress(10)
                        import time
                        time.sleep(1.0)
                        file_content = compressed_content                
                # For large files that were compressed, validate word count on compressed content
                if file_size_mb > 10:
                    status_text.text("📝 Analyzing compressed file content...")
                    progress_bar.progress(12)
                    
                    try:
                        pdf_analysis = analyze_pdf_content(file_content)
                        word_count = pdf_analysis['word_count']
                        
                        if word_count > 15000:
                            status_text.text("❌ Analysis failed: too many words even after compression")
                            st.error(f"❌ Compressed PDF still contains too many words ({word_count:,}). Maximum allowed: 15,000 words.")
                            st.info("💡 **Tip:** Try uploading a shorter document or specific chapters.")
                            st.session_state.is_generating_course = False
                            return
                        elif word_count == 0:
                            status_text.text("❌ Analysis failed: no text found")
                            st.error("❌ Could not extract text from the compressed PDF. Please try a different file.")
                            st.session_state.is_generating_course = False
                            return
                        else:
                            status_text.text(f"✅ Content validated: {word_count:,} words found")
                            progress_bar.progress(14)
                            
                    except Exception as e:
                        status_text.text("❌ Analysis failed: error reading content")
                        st.error(f"❌ Error analyzing compressed PDF: {str(e)}")
                        st.session_state.is_generating_course = False
                        return
                
                # Reset file pointer and generate course
                status_text.text("🚀 Starting course generation...")
                progress_bar.progress(15)
                
                course_data, error_message = generate_course(
                    file_content=file_content, 
                    status_callback=status_callback
                )
            else:
                # URL-based generation (no compression needed)
                course_data, error_message = generate_course(
                    file_url=pdf_url, 
                    status_callback=status_callback
                )
            
            if course_data and not error_message:
                # Process successful generation
                progress_bar.progress(100)
                status_text.text("✅ Course created successfully! Processing save...")

                if uploaded_file:
                    course_title = f"📄 {uploaded_file.name.replace('.pdf', '')}"
                else:
                    course_title = "🔗 Course from URL"

                generated_course_id = None  # Will store the ID if successfully saved
                save_error_occurred = False

                if MONGO_AVAILABLE:
                    try:
                        course_manager = get_course_manager()
                        is_guest = not st.session_state.get('authentication_status', False)
                        
                        if is_guest:
                            session_id = get_session_id()
                            creator = session_id
                        else:
                            session_id = None
                            creator = st.session_state.get('username', 'unknown_user')
                        
                        temp_mongo_id, save_db_error = course_manager.save_course(
                            course_data=course_data,
                            course_title=course_title,
                            creator=creator,
                            is_guest=is_guest,
                            session_id=session_id,
                            is_public=True 
                        )
                        
                        if save_db_error:
                            st.error(f"❌ Failed to save course to database: {save_db_error}")
                            save_error_occurred = True
                        else:
                            generated_course_id = temp_mongo_id
                            if generated_course_id: # Ensure generated_course_id is not None
                                st.query_params["course_id"] = str(generated_course_id)
                                status_text.text("✅ Course saved! Redirecting...")
                            else:
                                st.error("❌ Failed to get a valid course ID after saving.")
                                save_error_occurred = True
                                
                    except Exception as e_mongo_save:
                        st.error(f"❌ Critical error during course saving: {e_mongo_save}")
                        save_error_occurred = True
                else:
                    st.warning("⚠️ MongoDB not available. Course generated but not saved persistently.")
                    # For non-MongoDB (session-based) flow, we might need a different ID mechanism
                    # For now, if Mongo is the target, this is effectively a save failure for persistence.
                    save_error_occurred = True 

                if not save_error_occurred and generated_course_id:
                    st.session_state.current_course_id = generated_course_id
                    
                    if not st.session_state.get('authentication_status'):
                        increment_guest_course_count()
                    st.session_state.is_generating_course = False
                    st.session_state.current_uploaded_file = None
                    st.session_state.current_pdf_url = None
                    
                    import time
                    time.sleep(1.5) # Allow messages to be seen
                    st.switch_page("pages/3_Course.py")
                else:
                    # Save failed or MONGO_AVAILABLE was false and no alternative ID was generated
                    status_text.error("Course generation finished, but could not be saved for persistent access.")
                    st.session_state.is_generating_course = False
                    st.session_state.current_uploaded_file = None
                    st.session_state.current_pdf_url = None
                    # Do not redirect, allow user to see the error and try again.
                    
            else:  # error_message from local_backend.generate_course
                st.error(f"❌ {error_message}")
                st.session_state.is_generating_course = False
                st.session_state.current_uploaded_file = None
                st.session_state.current_pdf_url = None
                
        except Exception as e:
            st.error(f"❌ Error generating course: {str(e)}")
            st.session_state.is_generating_course = False
            st.session_state.current_uploaded_file = None
            st.session_state.current_pdf_url = None

def count_total_questions(course_data):
    """Count total questions in course recursively"""
    total = 0
    for section in course_data:
        # Count questions in main section
        if 'quiz' in section:
            total += len(section['quiz'])
        elif 'questions' in section:
            total += len(section['questions'])
        
        # Count questions in subsections
        if 'subsections' in section and section['subsections']:
            for subsection in section['subsections']:
                if 'quiz' in subsection:
                    total += len(subsection['quiz'])
                elif 'questions' in subsection:
                    total += len(subsection['questions'])
    return total

def show_course_history():
    """Show course history in sidebar"""
    if st.session_state.course_history:
        with st.sidebar:
            st.markdown("### 🏠 Navigation")
            if st.button("🏠 Home", use_container_width=True):
                st.rerun()
            
            st.markdown("### 📚 Your Courses")
            for course in st.session_state.course_history:                # Truncate long titles
                display_title = course['title']
                if len(display_title) > 25:
                    display_title = display_title[:22] + "..."
                if st.button(f"{display_title}", key=f"course_{course['id']}", use_container_width=True):
                    st.session_state.current_course_id = course['id']
                    st.switch_page("pages/3_Course.py")
              # Show user status
            st.markdown("---")
            if st.session_state.get('authentication_status'):
                st.success(f"👤 Logged in as {st.session_state.get('name', 'User')}")
            else:
                guest_count = get_guest_course_count()
                remaining = 3 - guest_count
                st.info(f"🎯 Guest: {remaining}/3 courses remaining")
                
# --- PDF Compression Functions ---
def compress_pdf(pdf_content, target_size_mb=10):
    """
    Compress a PDF using multiple strategies to achieve significant size reduction.
    
    Args:
        pdf_content (bytes): Original PDF content
        target_size_mb (int): Target size in MB
        
    Returns:
        tuple: (compressed_pdf_bytes, compression_ratio, success)
    """
    try:
        from PyPDF2 import PdfReader, PdfWriter
        
        # Check if compression is needed
        original_size = len(pdf_content)
        original_size_mb = original_size / (1024 * 1024)
        
        if original_size_mb <= target_size_mb:
            return pdf_content, 1.0, True
            
        # Strategy 1: Basic PyPDF2 compression
        pdf_reader = PdfReader(io.BytesIO(pdf_content))
        pdf_writer = PdfWriter()
        
        # Apply basic compression to all pages
        for page_num in range(len(pdf_reader.pages)):
            page = pdf_reader.pages[page_num]
            
            # Apply content stream compression
            try:
                page.compress_content_streams()
            except (AttributeError, Exception):
                pass
            
            pdf_writer.add_page(page)
        
        # Get compressed result
        compressed_pdf = io.BytesIO()
        pdf_writer.write(compressed_pdf)
        compressed_content = compressed_pdf.getvalue()
        compressed_size_mb = len(compressed_content) / (1024 * 1024)
        
        # If still too large, try page reduction strategy
        if compressed_size_mb > target_size_mb:
            total_pages = len(pdf_reader.pages)
            
            # Calculate how many pages we can keep
            target_ratio = target_size_mb / compressed_size_mb
            pages_to_keep = max(1, int(total_pages * target_ratio * 0.9))  # Keep 90% of calculated ratio for safety
            
            if pages_to_keep < total_pages:
                # Create a new PDF with subset of pages
                pdf_writer_subset = PdfWriter()
                
                for page_num in range(pages_to_keep):
                    page = pdf_reader.pages[page_num]
                    try:
                        page.compress_content_streams()
                    except Exception:
                        pass
                    pdf_writer_subset.add_page(page)
                
                # Get subset result
                subset_pdf = io.BytesIO()
                pdf_writer_subset.write(subset_pdf)
                subset_content = subset_pdf.getvalue()
                subset_size_mb = len(subset_content) / (1024 * 1024)
                
                if subset_size_mb <= target_size_mb:
                    compression_ratio = len(subset_content) / original_size
                    return subset_content, compression_ratio, True
        
        # Return the best compression we achieved
        compression_ratio = len(compressed_content) / original_size
        return compressed_content, compression_ratio, True
        
    except Exception:
        # If compression fails, return original content
        return pdf_content, 1.0, False

def smart_pdf_compression(pdf_content, target_size_mb=10):
    """
    Smart PDF compression with multiple strategies and detailed feedback.
    
    Args:
        pdf_content (bytes): Original PDF content
        target_size_mb (int): Target size in MB
        
    Returns:
        tuple: (final_pdf_bytes, final_size_mb, compression_ratio, success_message)
    """
    original_size = len(pdf_content)
    original_size_mb = original_size / (1024 * 1024)
    
    if original_size_mb <= target_size_mb:
        return pdf_content, original_size_mb, 1.0, "No compression needed"
    
    # Try aggressive compression
    compressed_content, compression_ratio, success = compress_pdf(pdf_content, target_size_mb)
    
    if success:
        final_size_mb = len(compressed_content) / (1024 * 1024)
        
        # Provide detailed feedback based on compression achieved
        if final_size_mb <= target_size_mb:
            if compression_ratio < 0.5:  # More than 50% reduction
                strategy = "Aggressive compression with significant size reduction"
            elif compression_ratio < 0.8:  # 20-50% reduction  
                strategy = "Standard compression"
            else:  # Less than 20% reduction
                strategy = "Basic compression"
                
            return compressed_content, final_size_mb, compression_ratio, f"✅ {strategy}: {original_size_mb:.1f}MB → {final_size_mb:.1f}MB"
        else:
            # Even with compression, still too large
            if compression_ratio < 0.7:  # At least 30% reduction achieved
                return compressed_content, final_size_mb, compression_ratio, f"⚠️ Compressed {original_size_mb:.1f}MB → {final_size_mb:.1f}MB but still above {target_size_mb}MB limit"
            else:
                return compressed_content, final_size_mb, compression_ratio, f"❌ Minimal compression achieved: {original_size_mb:.1f}MB → {final_size_mb:.1f}MB (still above {target_size_mb}MB)"
    else:
        return pdf_content, original_size_mb, 1.0, "❌ Compression failed - using original file"

if __name__ == "__main__":
    main()
