import streamlit as st
import os
import sys

# Add parent directory to path to import modules
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

# Add the parent directory (Quiz app) to sys.path to allow imports from it
# __file__ is pages/1_🏠_Home.py -> dirname is pages -> dirname is Quiz app
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


try:
    from mongo_auth import MongoAuthManager
    from mongo_course_manager import get_course_manager, get_session_id
    from local_backend import analyze_pdf_content, generate_course
    MONGO_AVAILABLE = True
except ImportError as e:
    # It's okay to call st.error here after set_page_config
    st.error(f"Failed to import MongoAuthManager or MongoCourseManager. Ensure mongo_auth.py and mongo_course_manager.py are in the correct path: {e}")
    MONGO_AVAILABLE = False
    # Allow guest access even if Mongo is down, but authenticated features will be limited.

# --- Get Cookie Manager from Session State ---
cookies = st.session_state.get('cookies')
if not cookies:
    st.error("Cookie manager not found in session state. Please run the app from the main entry point.")
    st.stop()

# Initialize cookies if they haven't been, e.g. on first run
# This needs to be called early, but after st.set_page_config
# We'll handle the st.stop() or alternative flow after page config.

AUTH_COOKIE_NAME = "username" # Consistent cookie name
GUEST_COURSES_COOKIE_NAME = "guest_courses_count" # Cookie to track guest course generation

# --- Authentication is now handled in main.py ---

# --- Guest Course Tracking Functions ---
def get_guest_course_count():
    """Get the number of courses generated by guest users from cookies"""
    if not cookies.ready():
        return 0
    try:
        return int(cookies.get(GUEST_COURSES_COOKIE_NAME, "0"))
    except (ValueError, TypeError):
        return 0

def increment_guest_course_count():
    """Increment the guest course count in cookies"""
    if not cookies.ready():
        return
    current_count = get_guest_course_count()
    new_count = current_count + 1
    cookies[GUEST_COURSES_COOKIE_NAME] = str(new_count)
    cookies.save()
    return new_count

def reset_guest_course_count():
    """Reset guest course count (called when user logs in)"""
    if cookies.ready():
        cookies[GUEST_COURSES_COOKIE_NAME] = "0"
        cookies.save()

def check_course_limit():
    """Check if user has reached the course generation limit"""
    if st.session_state.get('authentication_status'):
        return True # No limit for logged-in users
    
    # For guest users, check cookie-based count
    guest_count = get_guest_course_count()
    return guest_count < 3

def force_login_if_limit_reached():
    """Force login if guest user has reached the 3-course limit"""
    if not st.session_state.get('authentication_status'):
        guest_count = get_guest_course_count()
        if guest_count >= 3:
            st.warning("You have reached the guest limit of 3 courses. Please log in to create more.")
            st.page_link("app_pages/2_🔐_Login.py", label="Login / Sign Up", icon="🔐")
            st.stop()
    return False

# Initialize session state function
def initialize_session_state():
    """Initialize all session state variables"""
    if "current_section_index" not in st.session_state:  
        st.session_state.current_section_index = 0
    if "user_answers" not in st.session_state:
        st.session_state.user_answers = {}
    if "checked_answers" not in st.session_state:
        st.session_state.checked_answers = {}
    if "current_score" not in st.session_state:
        st.session_state.current_score = 0
    if "total_questions_in_course" not in st.session_state:
        st.session_state.total_questions_in_course = 0
    if "scored_correctly_keys" not in st.session_state:
        st.session_state.scored_correctly_keys = set()
    if "feedback" not in st.session_state:
        st.session_state.feedback = {}
    if "course_data" not in st.session_state:
        st.session_state.course_data = None
    if "error_message" not in st.session_state:
        st.session_state.error_message = None
    if "is_generating_course" not in st.session_state:
        st.session_state.is_generating_course = False
    if "courses_generated" not in st.session_state:
        # For guest users, load count from cookies; for logged-in users, always 0
        if st.session_state.get('authentication_status'):
            st.session_state.courses_generated = 0
        else:
            st.session_state.courses_generated = get_guest_course_count()
    if "authentication_status" not in st.session_state:
        st.session_state.authentication_status = None
    if "name" not in st.session_state:
        st.session_state.name = None
    if "username" not in st.session_state:
        st.session_state.username = None
    if "course_history" not in st.session_state:
        st.session_state.course_history = []
    if "current_course_id" not in st.session_state:
        st.session_state.current_course_id = None

# Initialize session state
initialize_session_state()

# Apply modern CSS styling
st.markdown("""
<style>
    /* Global styles */
    .stApp {
        background: linear-gradient(135deg, #0a0014 0%, #1a0033 100%);
    }
    
    /* Hide default sidebar */
    .css-1d391kg {
        padding-top: 1rem;
    }
    
    /* Center container */
    .main-container {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        text-align: center;
    }
    
    /* Title styling */
    .main-title {
        font-size: 3rem;
        font-weight: 700;
        background: linear-gradient(135deg, #9d00ff, #ff6b6b);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 2rem;
    }
      /* Pill button styling */
    .stButton > button {
        background: linear-gradient(135deg, #9d00ff, #7a00cc);
        color: white;
        border: none;
        border-radius: 50px;
        padding: 12px 30px;
        font-weight: 600;
        transition: all 0.3s ease;
        box-shadow: 0 4px 15px rgba(157, 0, 255, 0.3);
        width: 100%;
        font-size: 1rem;
    }
    
    .stButton > button:hover {
        background: linear-gradient(135deg, #7a00cc, #5c0099);
        transform: translateY(-2px);
        box-shadow: 0 8px 25px rgba(157, 0, 255, 0.4);
    }
    
    /* Input styling */
    .stTextInput > div > div > input {
        background: rgba(26, 0, 51, 0.8);
        border: 2px solid #9d00ff;
        border-radius: 25px;
        color: #ededed;
        padding: 12px 20px;
    }
    
    .stTextInput > div > div > input:focus {
        border-color: #ff6b6b;
        box-shadow: 0 0 15px rgba(157, 0, 255, 0.3);
    }
    
    /* File uploader enhanced styling */
    .stFileUploader {
        background: rgba(255, 255, 255, 0.03);
        border: 2px dashed #9d00ff;
        border-radius: 20px;
        padding: 2rem;
        text-align: center;
        transition: all 0.3s ease;
        margin: 1rem 0;
    }
    
    .stFileUploader:hover {
        border-color: #ff6b6b;
        background: rgba(255, 255, 255, 0.06);
        transform: translateY(-2px);
    }
    
    /* Tab styling */
    .stTabs [data-baseweb="tab-list"] {
        background: rgba(255, 255, 255, 0.05);
        border-radius: 25px;
        padding: 5px;
        gap: 10px;
        justify-content: center;
        margin-bottom: 2rem;
    }
    
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        border-radius: 20px;
        color: rgba(255, 255, 255, 0.7);
        padding: 12px 24px;
        font-weight: 600;
        transition: all 0.3s ease;
        border: none;
    }
    
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #9d00ff, #7a00cc);
        color: white;
        box-shadow: 0 4px 15px rgba(157, 0, 255, 0.3);
    }
    
    /* Progress bar styling */
    .stProgress > div > div > div > div {
        background: linear-gradient(135deg, #9d00ff, #ff6b6b);
        border-radius: 10px;
    }
    
    /* Success/Error/Warning message styling */
    .stSuccess, .stInfo, .stWarning, .stError {
        border-radius: 15px;
        border: none;
        padding: 1rem;
        margin: 1rem 0;
    }
    
    .stSuccess {
        background: linear-gradient(135deg, rgba(0, 255, 0, 0.1), rgba(0, 200, 0, 0.1));
        border-left: 4px solid #00ff00;
    }
    
    .stInfo {
        background: linear-gradient(135deg, rgba(0, 150, 255, 0.1), rgba(0, 100, 255, 0.1));
        border-left: 4px solid #0096ff;
    }
    
    .stWarning {
        background: linear-gradient(135deg, rgba(255, 165, 0, 0.1), rgba(255, 140, 0, 0.1));
        border-left: 4px solid #ffa500;
    }
    
    .stError {
        background: linear-gradient(135deg, rgba(255, 0, 0, 0.1), rgba(200, 0, 0, 0.1));
        border-left: 4px solid #ff0000;
    }
    
    /* Top navigation */
    .top-nav {
        position: fixed;
        top: 0;
        right: 0;
        padding: 1rem;
        z-index: 1000;
    }
</style>
""", unsafe_allow_html=True)

def main():
    """Main function to run the home page"""
    # Set page config is now in main.py
    
    # Attempt to auto-login from cookie (now handled globally in main.py)
    # No longer needed here: auto_login_from_cookie_home()

    # Initialize session state
    initialize_session_state()

    # Check if guest user has reached the course limit
    force_login_if_limit_reached()

    # Top navigation
    col1, col2, col3 = st.columns([6, 1, 1]) # Adjusted column ratio for better spacing
    
    with col2: # Login/User status
        if st.session_state.get('authentication_status'):
            # Display user name, truncate if too long for the button-like display
            display_name = st.session_state.get('name', st.session_state.get('username', 'User'))
            if len(display_name) > 15:
                display_name = display_name[:12] + "..."
            st.markdown(f"<div style='text-align: center; padding: 5px 0px; border: 1px solid #9d00ff; border-radius: 25px; background: rgba(157,0,255,0.1); color: #ededed;'>👤 {display_name}</div>", unsafe_allow_html=True)
        elif MONGO_AVAILABLE and cookies.ready():
            if st.button("🔐 Login", key="top_nav_login_btn", use_container_width=True):
                st.switch_page("app_pages/2_🔐_Login.py")
        # If not authenticated and auth unavailable, this column remains empty or shows a guest indicator if desired

    with col3: # Logout button
        if st.session_state.get('authentication_status'):
            if st.button("🚪 Logout", key="top_nav_logout_btn", use_container_width=True):
                logout_user_session() # Use the centralized logout function
                st.rerun()
        # If not authenticated, this column remains empty or could show a register link if col2 is for login

    # Main content container
    st.markdown('<div class="main-container">', unsafe_allow_html=True)
      # Main title
    st.markdown('<h1 class="main-title">What will you learn today?</h1>', unsafe_allow_html=True)    # Show status message
    if st.session_state.get('authentication_status'):
        st.success(f"🎉 Welcome back, {st.session_state.get('name', 'User')}! You have unlimited course generation.")
    else:
        # Force login if limit reached
        if force_login_if_limit_reached():
            return  # Stop execution if forcing login            
        # Show remaining courses for guest users
        guest_count = get_guest_course_count()
        remaining = 3 - guest_count
        if remaining > 0:
            st.info(f"🎯 Guest mode: {remaining} out of 3 free courses remaining")
        else:
            st.warning("🔒 You've used all 3 guest courses. Please login for unlimited access!")
    
    st.markdown("---")
    
    # Course Dashboard
    show_course_dashboard()
    
    st.markdown("---")

    # Input tabs
    tab1, tab2 = st.tabs(["📁 Upload File", "🔗 URL"])
    uploaded_file = None
    pdf_url = None
    
    with tab1:
        st.markdown("### Upload your PDF file")
        uploaded_file = st.file_uploader(
            "Choose a PDF file",
            type=["pdf"],
            help="Maximum file size: 10MB, Maximum words: 15,000",
            label_visibility="collapsed"
        )
        if uploaded_file:
            file_size = len(uploaded_file.getvalue())
            file_size_mb = file_size / (1024*1024)
              # Check file size limit (10MB)
            if file_size > 10 * 1024 * 1024:
                st.error(f"❌ File too large ({file_size_mb:.1f} MB). Maximum size is 10MB.")
                uploaded_file = None
            else:                # Analyze PDF content for word count
                try:
                    pdf_analysis = analyze_pdf_content(uploaded_file.getvalue())
                    word_count = pdf_analysis['word_count']
                    
                    if word_count > 15000:
                        st.error(f"❌ PDF contains too many words ({word_count:,}). Maximum allowed: 15,000 words.")
                        st.info("💡 **Tip:** Try uploading a shorter document or specific chapters.")
                        uploaded_file = None
                    elif word_count == 0:
                        st.error("❌ Could not extract text from this PDF. Please try a different file.")
                        uploaded_file = None
                    else:
                        st.success(f"📄 File uploaded: {uploaded_file.name} ({file_size_mb:.1f} MB)")
                        
                        if word_count > 12000:
                            st.warning("⚠️ Large document detected. Generation may take longer than usual.")
                            
                except Exception as e:
                    st.error(f"❌ Error analyzing PDF: {str(e)}")
                    uploaded_file = None
    
    with tab2:
        st.markdown("### Enter PDF URL")
        pdf_url = st.text_input(
            "PDF URL",
            placeholder="https://example.com/document.pdf",
            help="Enter a direct link to a PDF file",
            label_visibility="collapsed"
        )
        if pdf_url and not pdf_url.startswith(('http://', 'https://')):
            st.warning("⚠️ Please enter a valid URL starting with http:// or https://")
            pdf_url = None
        elif pdf_url:
            st.info("📝 **Note:** Word count and time estimation will be shown during generation for URL uploads.")
            st.warning("⚠️ **Limits:** Maximum 10MB file size, 15,000 words")
    
    # Generate button
    st.markdown("<br>", unsafe_allow_html=True)
    
    # Check if user can generate courses
    can_generate = check_course_limit()
    
    if st.session_state.get('is_generating_course', False):
        st.button("🤖 Generating Course...", disabled=True, key="generating_btn")        # Show progress
        show_generation_progress()
    elif can_generate:
        if st.button("✨ Generate Course", type="primary", key="generate_btn"):
            if uploaded_file or pdf_url:
                # Double-check course limit before generating
                if not check_course_limit():
                    st.error("🔐 Course limit reached. Please login to continue.")
                    return
                    
                # Store file data in session state for progress function
                st.session_state.current_uploaded_file = uploaded_file
                st.session_state.current_pdf_url = pdf_url
                
                # Set generating state immediately and rerun to update UI
                st.session_state.is_generating_course = True
                st.rerun()
            else:
                st.error("⚠️ Please upload a file or enter a URL first")
    else:
        st.warning("⚠️ You've reached the limit of 3 guest courses. Please login for unlimited access.")
        if st.button("🔐 Go to Login", type="primary"):
            st.switch_page("app_pages/2_🔐_Login.py")
    
    # Show course history in sidebar if available
    show_course_history()
    
    st.markdown('</div>', unsafe_allow_html=True)

def show_generation_progress():
    """Show course generation progress and start generation"""
    # Get the file data from session state (set when button was clicked)
    uploaded_file = st.session_state.get('current_uploaded_file')
    pdf_url = st.session_state.get('current_pdf_url')
    
    if uploaded_file or pdf_url:
        generate_and_redirect(uploaded_file, pdf_url)
    else:
        st.error("❌ No file or URL found for generation")

def generate_and_redirect(uploaded_file, pdf_url):
    """Generate course and redirect to course page with real-time progress"""
    # Set generation state
    st.session_state.is_generating_course = True
    
    # Create progress containers
    progress_container = st.container()
    with progress_container:
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        # Status callback function for real-time updates
        def status_callback(status_message, progress_percent):
            """Update progress and status in real-time"""
            progress_bar.progress(progress_percent / 100)
            status_text.text(status_message)
            import time
            time.sleep(1.5)  # Allow users to read the status
        
        try:
            # Generate course with real-time status updates
            if uploaded_file:
                uploaded_file.seek(0)  # Reset file pointer
                course_data, error_message = generate_course(
                    file_content=uploaded_file.read(), 
                    status_callback=status_callback
                )
            else:
                course_data, error_message = generate_course(
                    file_url=pdf_url, 
                    status_callback=status_callback
                )
            
            if course_data and not error_message:
                # Process successful generation
                progress_bar.progress(100)
                status_text.text("✅ Course created successfully! Processing save...")

                if uploaded_file:
                    course_title = f"📄 {uploaded_file.name.replace('.pdf', '')}"
                else:
                    course_title = f"🔗 Course from URL"

                generated_course_id = None  # Will store the ID if successfully saved
                save_error_occurred = False

                if MONGO_AVAILABLE:
                    try:
                        course_manager = get_course_manager()
                        is_guest = not st.session_state.get('authentication_status', False)
                        
                        if is_guest:
                            session_id = get_session_id()
                            creator = session_id
                        else:
                            session_id = None
                            creator = st.session_state.get('username', 'unknown_user')
                        
                        temp_mongo_id, save_db_error = course_manager.save_course(
                            course_data=course_data,
                            course_title=course_title,
                            creator=creator,
                            is_guest=is_guest,
                            session_id=session_id,
                            is_public=True 
                        )
                        
                        if save_db_error:
                            st.error(f"❌ Failed to save course to database: {save_db_error}")
                            save_error_occurred = True
                        else:
                            generated_course_id = temp_mongo_id
                            if generated_course_id: # Ensure generated_course_id is not None
                                st.query_params["course_id"] = str(generated_course_id)
                                status_text.text("✅ Course saved! Redirecting...")
                            else:
                                st.error("❌ Failed to get a valid course ID after saving.")
                                save_error_occurred = True
                                
                    except Exception as e_mongo_save:
                        st.error(f"❌ Critical error during course saving: {e_mongo_save}")
                        save_error_occurred = True
                else:
                    st.warning("⚠️ MongoDB not available. Course generated but not saved persistently.")
                    # For non-MongoDB (session-based) flow, we might need a different ID mechanism
                    # For now, if Mongo is the target, this is effectively a save failure for persistence.
                    save_error_occurred = True 

                if not save_error_occurred and generated_course_id:
                    st.session_state.current_course_id = generated_course_id
                    
                    if not st.session_state.get('authentication_status'):
                        increment_guest_course_count()
                    st.session_state.is_generating_course = False
                    st.session_state.current_uploaded_file = None
                    st.session_state.current_pdf_url = None
                    
                    import time
                    time.sleep(1.5) # Allow messages to be seen
                    st.switch_page("app_pages/3_Course.py")
                else:
                    # Save failed or MONGO_AVAILABLE was false and no alternative ID was generated
                    status_text.error("Course generation finished, but could not be saved for persistent access.")
                    st.session_state.is_generating_course = False
                    st.session_state.current_uploaded_file = None
                    st.session_state.current_pdf_url = None
                    # Do not redirect, allow user to see the error and try again.
                    
            else: # error_message from local_backend.generate_course
                st.error(f"❌ {error_message}")
                st.session_state.is_generating_course = False
                st.session_state.current_uploaded_file = None
                st.session_state.current_pdf_url = None
                
        except Exception as e:
            st.error(f"❌ Error generating course: {str(e)}")
            st.session_state.is_generating_course = False
            st.session_state.current_uploaded_file = None
            st.session_state.current_pdf_url = None

def count_total_questions(course_data):
    """Count total questions in course recursively"""
    total = 0
    for section in course_data:
        # Count questions in main section
        if 'quiz' in section:
            total += len(section['quiz'])
        elif 'questions' in section:
            total += len(section['questions'])
        
        # Count questions in subsections
        if 'subsections' in section and section['subsections']:
            for subsection in section['subsections']:
                if 'quiz' in subsection:
                    total += len(subsection['quiz'])
                elif 'questions' in subsection:
                    total += len(subsection['questions'])
    return total

def show_course_history():
    """Show course history in sidebar"""
    if st.session_state.course_history:
        with st.sidebar:
            st.markdown("### 🏠 Navigation")
            if st.button("🏠 Home", use_container_width=True):
                st.rerun()
            
            st.markdown("### 📚 Your Courses")
            for course in st.session_state.course_history:                # Truncate long titles
                display_title = course['title']
                if len(display_title) > 25:
                    display_title = display_title[:22] + "..."
                if st.button(f"{display_title}", key=f"course_{course['id']}", use_container_width=True):
                    st.session_state.current_course_id = course['id']
                    st.switch_page("app_pages/3_Course.py")
              # Show user status
            st.markdown("---")
            if st.session_state.get('authentication_status'):
                st.success(f"👤 Logged in as {st.session_state.get('name', 'User')}")
            else:
                guest_count = get_guest_course_count()
                remaining = 3 - guest_count
                st.info(f"🎯 Guest: {remaining}/3 courses remaining")

def show_course_dashboard():
    """Show user's course dashboard"""
    if MONGO_AVAILABLE:
        try:
            course_manager = get_course_manager()
            user_identifier = st.session_state.get('username')
            session_id_val = get_session_id()

            if st.session_state.get('authentication_status') and user_identifier:
                # Authenticated user
                courses, error = course_manager.get_user_courses(user_identifier, is_guest=False)
                stats, stats_error = course_manager.get_course_stats(user_identifier, is_guest=False)
            else:
                # Guest user - ensure session_id_val is used as user_identifier for guests
                courses, error = course_manager.get_user_courses(user_identifier=session_id_val, is_guest=True, session_id=session_id_val)
                stats, stats_error = course_manager.get_course_stats(user_identifier=session_id_val, is_guest=True, session_id=session_id_val)
            
            if courses and not error:
                st.markdown("### 📚 Your Recent Courses")
                
                # Show stats if available
                if stats and not stats_error:
                    col1, col2, col3, col4 = st.columns(4)
                    with col1:
                        st.metric("📖 Total Courses", stats.get('total_courses', 0))
                    with col2:
                        st.metric("❓ Total Questions", stats.get('total_questions', 0))
                    with col3:
                        st.metric("📄 Total Sections", stats.get('total_sections', 0))
                    with col4:
                        public_count = stats.get('public_courses', 0)
                        private_count = stats.get('private_courses', 0)
                        st.metric("🌍 Public / 🔒 Private", f"{public_count} / {private_count}")
                
                # Show recent courses
                st.markdown("#### Recent Courses")
                
                # Display courses in a grid
                cols = st.columns(3)
                for i, course in enumerate(courses[:6]):  # Show up to 6 recent courses
                    with cols[i % 3]:
                        course_title = course.get('title', 'Untitled Course')
                        course_id = course.get('course_id')
                        created_at = course.get('created_at', 'Unknown')
                        total_questions = course.get('total_questions', 0)
                        is_public = course.get('is_public', True)
                        
                        # Create course card
                        privacy_icon = "🌍" if is_public else "🔒"
                        
                        with st.container():
                            st.markdown(f"""
                            <div style="
                                border: 1px solid #9d00ff; 
                                border-radius: 15px; 
                                padding: 1rem; 
                                margin-bottom: 1rem;
                                background: rgba(157, 0, 255, 0.05);
                                transition: all 0.3s ease;
                            ">
                                <h4>{privacy_icon} {course_title[:30]}{'...' if len(course_title) > 30 else ''}</h4>
                                <p style="color: #888;">📊 {total_questions} questions</p>
                                <p style="color: #666; font-size: 0.8em;">📅 {created_at}</p>                            </div>
                            """, unsafe_allow_html=True)
                            
                            if st.button(f"▶️ Continue Learning", key=f"course_btn_{course_id}", use_container_width=True):
                                if course_id: # Ensure course_id is not None
                                    st.query_params["course_id"] = str(course_id)
                                    st.session_state.current_course_id = str(course_id)
                                    st.switch_page("app_pages/3_Course.py")
                                else:
                                    st.error("Course ID is missing, cannot navigate.")
                
                # Show "View All" button if there are more courses
                if len(courses) > 6:
                    st.info(f"... and {len(courses) - 6} more courses. Login to view your complete course library!")
            
            elif error:
                st.warning(f"⚠️ Could not load courses: {error}")
            else:
                # No courses found
                st.markdown("### 🚀 Ready to Get Started?")
                st.info("No courses yet. Upload a PDF or enter a URL below to generate your first interactive course!")
                
        except Exception as e:
            st.error(f"❌ Error loading course dashboard: {e}")
            # Fall back to session state
            show_session_course_dashboard()
    else:
        # Fall back to session state if MongoDB is not available
        show_session_course_dashboard()

def show_session_course_dashboard():
    """Show course dashboard from session state"""
    if 'course_history' in st.session_state and st.session_state.course_history:
        st.markdown("### 📚 Your Courses (Session)")
        
        # Simple metrics
        total_courses = len(st.session_state.course_history)
        st.metric("📖 Courses This Session", total_courses)
          # Show recent courses
        for i, course in enumerate(st.session_state.course_history[-3:]):  # Show last 3
            course_title = course.get('title', 'Untitled Course')
            if st.button(f"📄 {course_title}", key=f"session_course_btn_{i}", use_container_width=True):
                st.session_state.current_course_id = course['id']
                st.switch_page("app_pages/3_Course.py")
    else:
        st.markdown("### 🚀 Ready to Get Started?")
        st.info("No courses yet. Upload a PDF or enter a URL below to generate your first interactive course!")

main()
